version: '3.8'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: shop-backend
  #   restart: always
  #   environment:
  #     - NODE_ENV=developemnt
  #     - DATABASE_URL=postgres://postgres:postgres@shop-db:5432/mydb
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - db
  #   networks:
  #     - shop-network

  shop-db:
    image: postgres:13-alpine
    container_name: shop-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shop-network

volumes:
  postgres-data:

networks:
  shop-network:
    driver: bridge
